In [ ]:
## Simple Keras model

In [ ]:
from keras.models import Sequential
from keras.utils import np_utils
from keras.layers.core import Dense, Activation, Dropout

import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
print(train.shape)
print(test.shape)

(60000, 785)
(5000, 785)


In [4]:
test

id  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0        0       0       0       0       0       0       0       0       0   
1        1       0       0       0       0       0       0       0       0   
2        2       0       0       0       0       0       0       0       0   
3        3       0       0       0       0       0       0       0       0   
4        4       0       0       0       0       0       0       0       0   
...    ...     ...     ...     ...     ...     ...     ...     ...     ...   
4995  4995       0       0       0       0       0       0       0       0   
4996  4996       0       0       0       0       0       0       0       0   
4997  4997       0       0       0       0       0       0       0       0   
4998  4998       0       0       0       0       0       0       0       0   
4999  4999       0       0       0       0       0       0       0       0   

      pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0  ...         0         0         0         0         0         0   
1          0  ...         0         0         0         0         0         0   
2          0  ...         0         0         0         0         0         0   
3          0  ...         0         0         0         0         0         0   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
4995       0  ...         0         0         0         0         0         0   
4996       0  ...         0         0         0         0         0         0   
4997       0  ...         0         0         0         0         0         0   
4998       0  ...         0         0         0         0         0         0   
4999       0  ...         0         0         0         0         0         0   

      pixel780  pixel781  pixel782  pixel783  
0            0         0         0         0  
1            0         0         0         0  
2            0         0         0         0  
3            0         0         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
4995         0         0         0         0  
4996         0         0         0         0  
4997         0         0         0         0  
4998         0         0         0         0  
4999         0         0         0         0  

[5000 rows x 785 columns]

In [5]:
X_train = (train.iloc[:,1:].values).astype('float32') # all pixel values
Y_train = train.iloc[:,0].values.astype('int32') # only labels i.e targets digits
X_test = test.iloc[:,1:].values.astype('float32')

In [6]:
X_test.shape

(5000, 784)

In [7]:
# convert list of labels to binary class matrix
Y_train = np_utils.to_categorical(Y_train)

In [8]:
Y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [9]:
# pre-processing: divide by max and substract mean
scale = np.max(X_train)
X_train /= scale
X_test /= scale

In [10]:
mean = np.std(X_train)
X_train -= mean
X_test -= mean

In [11]:
X_train

array([[-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954],
       [-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954],
       [-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954],
       ...,
       [-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954],
       [-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954],
       [-0.24176954, -0.24176954, -0.24176954, ..., -0.24176954,
        -0.24176954, -0.24176954]], dtype=float32)

In [12]:
input_dim = X_train.shape[1]
classes = Y_train.shape[1]

In [13]:
# Here's a Deep Dumb MLP (DDMLP)
model = Sequential()
model.add(Dense(128, input_dim=input_dim))
model.add(Activation('relu'))
model.add(Dropout(0.15))
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.15))
model.add(Dense(classes))
model.add(Activation('softmax'))

2022-07-19 11:37:14.423910: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
# we'll use categorical xent for the loss, and RMSprop as the optimizer
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

In [15]:
print("Training...")
model.fit(X_train, Y_train, epochs=10, batch_size=16, validation_split=0.1)

Training...
Epoch 1/10
3375/3375 [==============================] - 4s 970us/step - loss: 0.2113 - val_loss: 0.0604
Epoch 2/10
3375/3375 [==============================] - 3s 998us/step - loss: 0.1278 - val_loss: 0.0607
Epoch 3/10
3375/3375 [==============================] - 3s 1ms/step - loss: 0.1155 - val_loss: 0.1036
Epoch 4/10
3375/3375 [==============================] - 3s 952us/step - loss: 0.1184 - val_loss: 0.1385
Epoch 5/10
3375/3375 [==============================] - 3s 973us/step - loss: 0.1175 - val_loss: 0.1177
Epoch 6/10
3375/3375 [==============================] - 3s 945us/step - loss: 0.1170 - val_loss: 0.1683
Epoch 7/10
3375/3375 [==============================] - 3s 946us/step - loss: 0.1190 - val_loss: 0.1451
Epoch 8/10
3375/3375 [==============================] - 3s 946us/step - loss: 0.1193 - val_loss: 0.2523
Epoch 9/10
3375/3375 [==============================] - 3s 928us/step - loss: 0.1189 - val_loss: 0.1527
Epoch 10/10
3375/3375 [==============================]

In [16]:
print("Generating test predictions...")


predict_x=model.predict(X_test) 
classes_x=np.argmax(predict_x,axis=1)

Generating test predictions...


In [17]:
classes_x

array([3, 0, 2, ..., 1, 6, 3])

In [19]:
def write_preds(preds, fname):
    pd.DataFrame({"ImageId": list(range(1,len(preds)+1)), "Label": preds}).to_csv(fname, index=False, header=True)

write_preds(classes_x, "predictions.csv")
#print(preds)

In [ ]:
X_train.shape

In [ ]:
X_test.shape